// tslint:disable
/**
 * JapaniseTextClassifierFunction
 * For hosting JapaniseTextClassifier on Azure Functions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ResponseCategories,
    ResponseCategoriesFromJSON,
    ResponseCategoriesToJSON,
    ResponseRequest,
    ResponseRequestFromJSON,
    ResponseRequestToJSON,
} from './';

/**
 * 
 * @export
 * @interface Response
 */
export interface Response {
    /**
     * 
     * @type {ResponseRequest}
     * @memberof Response
     */
    request?: ResponseRequest;
    /**
     * 
     * @type {boolean}
     * @memberof Response
     */
    hasError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Response
     */
    translatedText?: string;
    /**
     * 
     * @type {Array<ResponseCategories>}
     * @memberof Response
     */
    categories?: Array<ResponseCategories>;
}

export function ResponseFromJSON(json: any): Response {
    return {
        'request': !exists(json, 'Request') ? undefined : ResponseRequestFromJSON(json['Request']),
        'hasError': !exists(json, 'HasError') ? undefined : json['HasError'],
        'translatedText': !exists(json, 'TranslatedText') ? undefined : json['TranslatedText'],
        'categories': !exists(json, 'Categories') ? undefined : (json['Categories'] as Array<any>).map(ResponseCategoriesFromJSON),
    };
}

export function ResponseToJSON(value?: Response): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'Request': ResponseRequestToJSON(value.request),
        'HasError': value.hasError,
        'TranslatedText': value.translatedText,
        'Categories': value.categories === undefined ? undefined : (value.categories as Array<any>).map(ResponseCategoriesToJSON),
    };
}


