// tslint:disable
/**
 * JapaniseTextClassifierFunction
 * For hosting JapaniseTextClassifier on Azure Functions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseRequest
 */
export interface ResponseRequest {
    /**
     * 
     * @type {string}
     * @memberof ResponseRequest
     */
    translatorName?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseRequest
     */
    classifierName?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseRequest
     */
    text?: string;
}

export function ResponseRequestFromJSON(json: any): ResponseRequest {
    return {
        'translatorName': !exists(json, 'TranslatorName') ? undefined : json['TranslatorName'],
        'classifierName': !exists(json, 'ClassifierName') ? undefined : json['ClassifierName'],
        'text': !exists(json, 'Text') ? undefined : json['Text'],
    };
}

export function ResponseRequestToJSON(value?: ResponseRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'TranslatorName': value.translatorName,
        'ClassifierName': value.classifierName,
        'Text': value.text,
    };
}


