// tslint:disable
/**
 * JapaniseTextClassifierFunction
 * For hosting JapaniseTextClassifier on Azure Functions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseCategories
 */
export interface ResponseCategories {
    /**
     * 
     * @type {string}
     * @memberof ResponseCategories
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponseCategories
     */
    score?: number;
}

export function ResponseCategoriesFromJSON(json: any): ResponseCategories {
    return {
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'score': !exists(json, 'Score') ? undefined : json['Score'],
    };
}

export function ResponseCategoriesToJSON(value?: ResponseCategories): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'Name': value.name,
        'Score': value.score,
    };
}


