// tslint:disable
/**
 * JapaniseTextClassifierFunction
 * For hosting JapaniseTextClassifier on Azure Functions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Request,
    RequestFromJSON,
    RequestToJSON,
    Response,
    ResponseFromJSON,
    ResponseToJSON,
} from '../models';

export interface ClassifyJapaniseTextRequest {
    body?: Request;
}

/**
 * no description
 */
export class ClassificationApi extends runtime.BaseAPI {

    /**
     */
    async classifyJapaniseTextRaw(requestParameters: ClassifyJapaniseTextRequest): Promise<runtime.ApiResponse<Response>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/classify`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

   /**
    */
    async classifyJapaniseText(requestParameters: ClassifyJapaniseTextRequest): Promise<Response> {
        const response = await this.classifyJapaniseTextRaw(requestParameters);
        return await response.value();
    }

}
