name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - name: Build JapaniseTextClassifier
      run: dotnet build ./JapaniseTextClassifier/JapaniseTextClassifier.csproj
    - name: Build JapaniseTextClassifierConsole
      run: dotnet build ./JapaniseTextClassifierConsole/JapaniseTextClassifierConsole.csproj
    - name: Build JapaniseTextClassifierFunction
      run: dotnet build ./JapaniseTextClassifierFunction/JapaniseTextClassifierFunction.csproj
