name: Release JapaniseTextClassifier

on:
  push:
    branches:
    - release/nupkg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - run: dotnet build --configuration Release
    - run: dotnet nuget push JapaniseTextClassifier/bin/Release/JapaniseTextClassifier.*.nupkg -k $NUGET_OLG_API_KEY -s https://api.nuget.org/v3/index.json
      env:
        NUGET_OLG_API_KEY: ${{ secrets.NUGET_OLG_API_KEY }}
    - uses: actions/upload-artifact@master
      with:
        name: JapaniseTextClassifier
        path: JapaniseTextClassifier/bin/Release/netstandard2.0
    - uses: actions/upload-artifact@master
      with:
        name: JapaniseTextClassifierConsole
        path: JapaniseTextClassifierConsole/bin/Release/netcoreapp2.2
